### ISSUE TITLE
Passage sur slack

### ISSUE THREAD

**Issue by eroween** [WorldsParticle/Engine#100]
Je laisse la question ouverte a débat, personnellement j'aime beaucoup l'outil, ça pourrais être vraiment sympas d'avoir un slack pour la team.

De plus l'intégration avec Travis est vraiment bonne, je sais pas si vous avez déjà utilisé slack pour vos projets. Pour ma part j'en ai toujours un agréable souvenir.

**Comment by lefebv-z** [comment]
Je l'ai utilisé vite fait un jour mais pas assez pour m'en faire un avis. Mais un autre groupe m'en a parlé, ça m'intéresserait aussi. On en parlera pendant la prochaine reu.
