### ISSUE TITLE
Organisation de la semaine

### ISSUE THREAD

**Issue by AnonymOwl** [WorldsParticle/Engine#157]
Voir mode d'emploi : 
https://docs.google.com/document/d/1UWD0YiVf2Edn4iCe8oLolAGuPbLFdW_BuJbj0BxxqBs/edit#

**Comment by lefebv-z** [comment]
Vu que j'ai pas encore listé les choses à faire; je pense que je vais pas mal t'aider là dessus pour cette semaine benji. En espérant que j'ai moins besoin de le faire la semaine d'après.
