### ISSUE TITLE
[3] Remplacer le QGLWidget

### ISSUE THREAD

**Issue by Thibaud-fdb** [WorldsParticle/Engine#21]
Remplacer le GLWidget actuel (celui dans la fenêtre principale de l'interface) par la GLWindows qu'on utilise actuellement (Windows qui sera 'docké' dans l'interface). Lorsqu'on appuiera sur "explorer", cette windows sortira de l'interface comme c'est le cas actuellement.

La caméra et les renderers seront différents selon si l'état est "exploration" ou "édition / prévisualisation"

**Comment by eroween** [comment]
Plus de Qt dans ce projet.
